branches:
  except:
#   - log-basic
   
sudo: false

language: cpp

compiler:
  - gcc

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    packages:
      - ccache
      - gfortan #for silo
      - libhdf5-serial-dev #for silo
      - liblapack-dev
      - libblas-dev
      - libopenmpi-dev
      - openmpi-bin
      - gcc-4.8
      - g++-4.8
      
env:
  matrix: 
    # - COEVP_MPI=no  SILO=no  FLANN=no  REDIS=no  TWEMPROXY=no  LOGGER=no
    # - COEVP_MPI=no  SILO=no  FLANN=no  REDIS=no  TWEMPROXY=yes LOGGER=no
    # - COEVP_MPI=no  SILO=yes FLANN=no  REDIS=no  TWEMPROXY=no  LOGGER=no
    # - COEVP_MPI=no  SILO=yes FLANN=no  REDIS=no  TWEMPROXY=yes LOGGER=no
    - COEVP_MPI=no  SILO=yes FLANN=no  REDIS=yes TWEMPROXY=no  LOGGER=yes
    # - COEVP_MPI=no  SILO=yes FLANN=no  REDIS=yes TWEMPROXY=yes LOGGER=no
    # - COEVP_MPI=no  SILO=yes FLANN=yes REDIS=no  TWEMPROXY=no  LOGGER=yes
    # - COEVP_MPI=no  SILO=yes FLANN=yes REDIS=no  TWEMPROXY=yes LOGGER=no
    # - COEVP_MPI=no  SILO=yes FLANN=yes REDIS=yes TWEMPROXY=no  LOGGER=yes
    # - COEVP_MPI=no  SILO=yes FLANN=yes REDIS=yes TEMPROXY=yes  LOGGER=no
    # - COEVP_MPI=yes SILO=yes FLANN=yes REDIS=yes TWEMPROXY=no NP=1 LOGGER=no
    # - COEVP_MPI=yes SILO=yes FLANN=yes REDIS=yes TWEMPROXY=yes NP=1 LOGGER=yes
    # - COEVP_MPI=yes SILO=yes FLANN=yes REDIS=yes NP=4 LOGGER=no

before_script:
  - export PATH="/usr/lib/ccache:$PATH"

script:
  - make -j2 COEVP_MPI=${COEVP_MPI} REDIS=${REDIS} FLANN=${FLANN} SILO=${SILO} LOGGER=${LOGGER} && 
    make get_reference &&
    { [[ ${SILO} = no ]] || make test COEVP_MPI=${COEVP_MPI} REDIS=${REDIS} FLANN=${FLANN} SILO=${SILO} MPIRUN="${NP:+mpirun -np ${NP}}"; }

cache:
  directories:
    - $HOME/.ccache

notifications:
  email:
    - tabasco-dev@lanl.gov  
